/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5ea9983b82f82d390e78048a
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// FREELANCER
export const CREATE_FREELANCER_SUCCESS = "CREATE_FREELANCER_SUCCESS";
export const DELETE_FREELANCER_SUCCESS = "DELETE_FREELANCER_SUCCESS";
export const GET_FREELANCER_SUCCESS = "GET_FREELANCER_SUCCESS";
export const LIST_FREELANCER_SUCCESS = "LIST_FREELANCER_SUCCESS";
export const UPDATE_FREELANCER_SUCCESS = "UPDATE_FREELANCER_SUCCESS";

// INVESTOR
export const CREATE_INVESTOR_SUCCESS = "CREATE_INVESTOR_SUCCESS";
export const DELETE_INVESTOR_SUCCESS = "DELETE_INVESTOR_SUCCESS";
export const GET_INVESTOR_SUCCESS = "GET_INVESTOR_SUCCESS";
export const LIST_INVESTOR_SUCCESS = "LIST_INVESTOR_SUCCESS";
export const UPDATE_INVESTOR_SUCCESS = "UPDATE_INVESTOR_SUCCESS";

// MENTOR
export const CREATE_MENTOR_SUCCESS = "CREATE_MENTOR_SUCCESS";
export const DELETE_MENTOR_SUCCESS = "DELETE_MENTOR_SUCCESS";
export const GET_MENTOR_SUCCESS = "GET_MENTOR_SUCCESS";
export const LIST_MENTOR_SUCCESS = "LIST_MENTOR_SUCCESS";
export const UPDATE_MENTOR_SUCCESS = "UPDATE_MENTOR_SUCCESS";

// PARTNER
export const CREATE_PARTNER_SUCCESS = "CREATE_PARTNER_SUCCESS";
export const DELETE_PARTNER_SUCCESS = "DELETE_PARTNER_SUCCESS";
export const GET_PARTNER_SUCCESS = "GET_PARTNER_SUCCESS";
export const LIST_PARTNER_SUCCESS = "LIST_PARTNER_SUCCESS";
export const UPDATE_PARTNER_SUCCESS = "UPDATE_PARTNER_SUCCESS";

// STARTUP
export const CREATE_STARTUP_SUCCESS = "CREATE_STARTUP_SUCCESS";
export const DELETE_STARTUP_SUCCESS = "DELETE_STARTUP_SUCCESS";
export const GET_STARTUP_SUCCESS = "GET_STARTUP_SUCCESS";
export const LIST_STARTUP_SUCCESS = "LIST_STARTUP_SUCCESS";
export const UPDATE_STARTUP_SUCCESS = "UPDATE_STARTUP_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
